apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: student-api/database
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: student-api/database
        property: password
